spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/jpa-auditing-envers-kopring
      username: taesu
      password:
      maximum-pool-size: 5
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone=UTC:
      hibernate.envers.autoRegisterListeners: false
      org.hibernate.envers.audit_table_suffix: _HIS
      org.hibernate.envers.modified_flag_suffix: _CHANGED
      org.hibernate.envers.modified_column_naming_strategy: improved
  jackson:
    time-zone: UTC

debug: true

logging:
  level:
    org.hibernate.sql: DEBUG
    org.springframework.orm.jpa: DEBUG
