spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/jpa-auditing-envers-kopring
      username: taesu
      password:
      maximum-pool-size: 5
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone=UTC:
  jackson:
    time-zone: UTC

debug: true

logging:
  level:
    org.hibernate.sql: DEBUG
    org.springframework.orm.jpa: DEBUG
